#!/usr/bin/env python3
import requests
import json
from datetime import datetime
from pathlib import Path
from contextlib import contextmanager
import shutil

class FormatStrategy:
    @staticmethod
    def txt(ips, _): return '\n'.join(ips)
    
    @staticmethod
    def list(ips, _): 
        return '\n'.join(f"IP-CIDR{'6' if ':' in ip else ''},{ip}" for ip in ips)
    
    @staticmethod
    def yaml(ips, _): 
        return 'payload:\n' + '\n'.join(f"  - '{ip}'" for ip in ips)
    
    @staticmethod
    def json(ips, _): 
        return json.dumps({"version":2,"rules":[{"ip_cidr":ips}]}, indent=2)
    
    @staticmethod
    def snippet(ips, policy): 
        return '\n'.join(f"ip{'6' if ':' in ip else ''}-cidr, {ip}, {policy}" for ip in ips)

@contextmanager
def temp_dir(name):
    path = Path(name)
    path.mkdir(exist_ok=True)
    yield path
    shutil.rmtree(path)  

def generate(name, urls, policy):
    output_dir = Path.cwd()
    output_dir.mkdir(exist_ok=True, parents=True)
    
    ips = [ln for url in urls 
          for ln in requests.get(url).text.splitlines() 
          if ln.strip() and not ln.startswith('#')]
    
    header = f"# Generated by https://github.com/caocaocc/rule-set\n"\
             f"# Last Modified: {datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S UTC')}\n\n"
    
    for fmt in FormatStrategy.__dict__:
        if not fmt.startswith('_'):
            fmt_header = header if fmt != 'json' else ""
            content = fmt_header + getattr(FormatStrategy, fmt)(ips, policy)
            output_path = output_dir / f'{name}-ip.{fmt}'
            output_path.write_text(content)
            print(f"Generated file: {output_path.absolute()}")
    
    print(f"Generated {name}-ip.{{txt,list,yaml,json,snippet}}")
    return len(ips)

if __name__ == "__main__":
    results = [
        generate('cn', [
            'https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt',
            'https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt'
        ], 'direct'),
        generate('telegram', ['https://core.telegram.org/resources/cidr.txt'], 'proxy'),
        generate('private', ['https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/private.txt'], 'direct')
        
    ]
    print("\nTotal entries:")
    for name, count in zip(['CN', 'Telegram', 'Private'], results):
        print(f"{name}: {count}") 
